# Site settings
title: MehrAvar Kashiri
email: mehravaaar@gmail.com
description: MehrAvar Kashiri's portfolio
more: I am a freelance Graphic and motion designer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

instagram_username: packetstudio
twitter_username: mehravaaar
github_username: mehravaaar

# Build settings
markdown: kramdown