# Site settings
title: MehrAvar Kashiri
email: mehravaaar@gmail.com
description: MehrAvar Kashiri's portfolio
more: I am a freelance Graphic and motion designer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

instagram_username: packetstudio
twitter_username: mehravaaar
github_username: mehravaaar
linkedin_username: mehravar-kashiri

# Build settings
markdown: kramdown

#   Permalinks allow us to structure the directories of our source code different 
#   from the directories in our output.
#   permalink: /:categories/:year/:month/:day/:title/   # or use >> permalink: pretty
permalink: /:categories/:title

#   Collections are a great way to group related content like members of a team or 
#   talks at a conference.
collections:
  motion_graphy:
    output: true
    permalink: /:collection/:name

#You can access a snippet of a posts’s content by using excerpt variable on a post. By default this is the first paragraph of content in the post,
#however it can be customized by setting a excerpt_separator variable in front matter or _config.yml.
excerpt_separator: <!--more-->